---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: workshop2025
stringData:
  username: appuser
  postgres-password: secretpassword
  database: appdb
  password: secretpassword
