---

fullnameOverride:  "postgresql"

global:
  postgresql:
    auth:
      username: appuser
      database: appdb
      existingSecret: postgres-secret


primary:
  pgHbaConfiguration: |-
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             0.0.0.0/0               md5

  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
