---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: workshop2025
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicasNumber }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}"
          env:
            - name: POSTGRES_SERVER_HOST
              value: "{{ .Values.env.POSTGRES_SERVER_HOST }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.env.POSTGRES_PORT }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: CLIENT_URL
              value: "{{ .Values.env.CLIENT_URL }}"
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: JWT_KEY
              value: "{{ .Values.env.JWT_KEY }}"
            - name: RUN_MIGRATION
              value: "{{ .Values.env.RUN_MIGRATION }}"

          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["nc", "-z", "postgresql", "5432"]
            initialDelaySeconds: 10
            periodSeconds: 20
