---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.name }}
  namespace: workshop2025
data:
  nginx.conf: |
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 3000;
            server_name localhost;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri /index.html;
            }

            location /api/ {
                proxy_pass http://backend-service:8081;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
