---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: workshop2025
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
